apiVersion: v1
kind: Service
metadata:
  name: backend-mock
  namespace: mcco
spec:
  type: NodePort
  selector:
    app: backend-mock
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800    # access at http://localhost:30800
