apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mcco
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300    # access at http://localhost:30300
